# Site
#repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
baseurl: "/resume_eng"
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Dang Jun (Frank) We
title: Software Engineer
email: djwe1992@gmail.com
# website: www.github.com/frank217

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  frank217
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: dang-jun-we
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: /images/Resume_Dang Jun We_2022_ENG.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Resume PDF
resume: 
 - title: Resume Download
 
support_second_language: "../resume"


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Back-end Software Engineer with 3 years of experience. During 3 years, worked at Viagogo / Stubhub automating and improving Paid Search as part of Performance marketing team based in New York. 
  Experience with C# / Javascript / Python.<br/>
  Participated in **full stack** website develplment for** in house A/B testing website**,
  as well as **data pipelining** with Azure Data Explorer(Kusto) and SQL.<br/>
  Experience with developing Google Ads Compliance, back end integration between Viagogo and Stubhub merger and other bugging and improvements to ads aumation.<br/>
  Startup experience on building iOS SNS applicaiton for furniture and interior design community with 2 other fouding members. 
  
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Viagogo / Stubhub <br/> US - New York
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Performance Marketing Team Software Engineer
        caption:  2019.07 - 2022.07
        quote: >
          Utilize performance marketing to improve ticket sales.
        description: | # this will include new lines to allow paragraphs
            * **Developed and improved automation of Paid Search**, using Google Ads / Google Adwords(deprecated) / Microsoft Ads(Bing) API tools.
            * Back end integration between Viagogo and Stubhub. Developed addition data pipelining and automation process for Stubhub, more than doubling the traffic with paid search on the day of DB integration. 
            * Developed funcitonality to find new keywords using Google Keyword Planner API. Using **4k keywords** that constitutes 90% of sales, **found new 140k keywords**.
            * Implmented RateLimiter to resolve API ratelimit related issues. Decreased **80% of ratelimit reqeusts**, thus reducing resources used to create request and log request result
            by issuing semi-randomized gatetime upon ratelimit. Later categorized requests and utilize its data to improve ratelimit from highest occuring reqeuest.
            * Developed functionality to alter Bidding Strategy depening on db data. Allowed usage of Target ROAS(Bidding Strategy) to reduce excessive Bidding request by 50%, which also helped with Ratelimit issue. 
            * In order to comply with Google Ads, created **Compliance package** used in almost every application. Compliacne package decides if ads are compliant based on db data that product team applies for
             noncompliant keywords and blacklisted country. Package was used during creating of ads, request, and reports to prevent compliance issue and log any noncompliance issue found. 
            * Participated in creating in-house A/B testing website as fullstack engineer to improve visibility on Test state and data as well as streamlining A/B test process. 
            Supported front-end pages and back-end db integration for creation, development and deployment of A/B test to QA and PROD as well as dashboard for completed and ongoing test data.
            * Expedited A/B testing process by debugging and tunning 14 SQL procs used by A/B Testing.
      
      - layout: left
        title: HueSpace (Startup)
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Lead Software Engineer
        caption:  2020.07 - 2020.12
        quote: >
          SNS for interior and funiture lovers!
        description: | # this will include new lines to allow paragraphs
            * iOS developed with **Swift and XCode**. 
            * Developed fullstack SNS similar to Instatgram.
            * Implemented Nosql DB with **Firebase**. 
            * Participated in UX/UI process to improve user experience.
            * Implement post,comment,like, tag and search functionality. Posts contains tagging of colors and furniture manufacturer in the post, which can be used for search and recommendation.  
            * Suggest most liked posts and set of posts with new color scheme for user to explore new posts.
            * Integrated Facebook and Google Login.

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        #caption: 2017 - 2019
        #sub_title: BA Computer Science
        #quote: >
        #  Go Rice Owls
        description: | # this will include new lines to allow paragraphs
          * Language : C#(Visual Studio), Python(Visual Studio Code), Java(IntelliJ)
          * MYSQL(SQL Server Management Studio & Redgate), NoSQL(Firebase), Kusto(Azure Data Explorer)
          * Azure, Microsoft Devops tools.

      - layout: left
        title: Frontend
        #caption: 2017 -  2019
        #sub_title: BA Computer Science
        #quote: >
        #  Go Rice Owls
        description: | # this will include new lines to allow paragraphs
          * Language : Javascript, Html, CCS,
          * DJango, Bootstropm, NodeJS
          * Swift(iOS 개발)
    
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rice University
        caption: 2017 - 2019
        sub_title: BA Computer Science
        quote: >
          Coursed taken ad Computer Science major that became basis my career. 
        description: | # this will include new lines to allow paragraphs
          * Advanced OOP & Design : Improved understadning of OOP(object oriented programing) by devloping various applicaiton with Java.
          * Parallel Programing : Learn concept of parrallel programing and how to properly use it using AWS EC2 and EMR.
          * Tools & models for Data Science : Improve understadning and usage of SQL. 
          * Reasoning of Algorithm : Learn runtime analysis of diverse data structure and algorith. Later participated and teaching assistanct to improve such skill set. 
          * Artificial intelligence : Learn and implement diverse instances of AI. 
          * Linear Algebra : Basis for ML/AI courses 
          * Linear Regression : Basis for ML/AI courses  
          * Probabilistic Algorithms and Data Structures : Nondeterministic algorithm course. Unlike Deterministic algorithm course where we learns to give and take bewtween Memory and Runtime, 
          Nondeterministic algorithm learns to give and take between probability on Accuracy and Runtime and memory. Deals with how google and Amazon decrease search runtime. 
          * Operating System : Learn and implementation OS System.    
          * Principle of Programming Languages : Learn and implement programming languages, develop functional programming language.

#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
#
#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
